import { router } from 'expo-router';
import { StyleSheet, Text, TextInput, View } from 'react-native';
import { AppTitle, Card, PrimaryButton, Screen, SectionTitle } from '../../src/components/ui';
import { colors } from '../../src/theme';

export default function HomeScreen() {
  return <Screen><View style={styles.top}><Text style={styles.logo}>SafePath</Text><Text accessibilityLabel="Profile" style={styles.profile}>AK</Text></View>
    <AppTitle eyebrow="Good evening, Ananya" title="Where are you going?" subtitle="Plan with context, not just travel time." />
    <Card><Text style={styles.locationLabel}>CURRENT LOCATION</Text><View style={styles.locationRow}><View style={styles.dot} /><View><Text style={styles.location}>Chennai Central</Text><Text style={styles.locationDetail}>Using a sample location</Text></View></View></Card>
    <View style={{ gap: 9 }}><Text style={styles.inputLabel}>Destination</Text><TextInput accessibilityLabel="Destination" placeholder="Search an area or landmark" placeholderTextColor="#7C8B91" style={styles.input} /><PrimaryButton label="Find safe routes" onPress={() => router.push('/route-search')} /></View>
    <View style={{ gap: 12 }}><SectionTitle title="Quick access" /><View style={styles.quickRow}><Card style={styles.quickCard}><Text style={styles.quickIcon}>⌁</Text><Text style={styles.quickTitle} onPress={() => router.push('/emergency-contacts')}>Emergency contacts</Text><Text style={styles.quickBody}>2 saved contacts</Text></Card><Card style={styles.quickCard}><Text style={styles.quickIcon}>↗</Text><Text style={styles.quickTitle} onPress={() => router.push('/route-results')}>Recent routes</Text><Text style={styles.quickBody}>View route previews</Text></Card></View></View>
    <PressableSos />
  </Screen>;
}

function PressableSos() { return <View style={styles.sos}><View style={{ flex: 1, gap: 4 }}><Text style={styles.sosTitle}>Emergency SOS</Text><Text style={styles.sosBody}>Open the emergency action screen</Text></View><Text accessibilityRole="button" onPress={() => router.push('/sos')} style={styles.sosAction}>OPEN</Text></View>; }
const styles = StyleSheet.create({ top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, logo: { color: colors.ink, fontWeight: '900', fontSize: 20 }, profile: { backgroundColor: colors.primarySoft, color: colors.primaryDark, borderRadius: 20, overflow: 'hidden', paddingHorizontal: 11, paddingVertical: 8, fontWeight: '800' }, locationLabel: { color: colors.muted, fontSize: 11, letterSpacing: 1, fontWeight: '800' }, locationRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 12 }, dot: { width: 12, height: 12, borderRadius: 6, backgroundColor: colors.primary }, location: { color: colors.ink, fontSize: 17, fontWeight: '800' }, locationDetail: { color: colors.muted, marginTop: 3 }, inputLabel: { color: colors.ink, fontSize: 14, fontWeight: '700' }, input: { minHeight: 52, borderRadius: 14, backgroundColor: colors.surface, borderColor: colors.line, borderWidth: 1, paddingHorizontal: 15, fontSize: 16, color: colors.ink }, quickRow: { flexDirection: 'row', gap: 12 }, quickCard: { flex: 1, minHeight: 138, gap: 6 }, quickIcon: { color: colors.primary, fontSize: 25 }, quickTitle: { color: colors.ink, fontSize: 15, fontWeight: '800', lineHeight: 20 }, quickBody: { color: colors.muted, fontSize: 12, lineHeight: 17 }, sos: { flexDirection: 'row', alignItems: 'center', padding: 17, borderRadius: 18, backgroundColor: colors.dangerSoft, borderWidth: 1, borderColor: '#F4C6D0' }, sosTitle: { color: colors.danger, fontWeight: '900', fontSize: 17 }, sosBody: { color: '#7F3042', fontSize: 13 }, sosAction: { color: colors.danger, fontWeight: '900', fontSize: 13, letterSpacing: 0.7, padding: 8 } });
